import { loadMojo } from "../js/mojowasm.js";
import { readFile } from "node:fs/promises";
const m = await loadMojo(new Uint8Array(await readFile(new URL("../build/kernels.wasm", import.meta.url))));
const n = 1000;
const a = m.allocF64(n), b = m.allocF64(n);
const av = Array.from({length:n},(_,i)=>i*0.5), bv = Array.from({length:n},(_,i)=>i%7);
a.set(av); b.set(bv);
const expSum = av.reduce((x,y)=>x+y,0);
const expDot = av.reduce((s,x,i)=>s+x*bv[i],0);
console.log("sum", m.exports.sum(a.ptr,n), "exp", expSum);
console.log("dot", m.exports.dot(a.ptr,b.ptr,n), "exp", expDot);
console.log("heap_sum", m.exports.heap_sum(1000), "exp", Array.from({length:1000},(_,i)=>i*0.5).reduce((x,y)=>x+y,0));
const M=32,K=32,N=32;
const A=m.allocF64(M*K).set(Array.from({length:M*K},(_,i)=>(i%13)*0.25));
const B=m.allocF64(K*N).set(Array.from({length:K*N},(_,i)=>(i%5)*0.5));
const C=m.allocF64(M*N);
m.exports.matmul(A.ptr,B.ptr,C.ptr,M,K,N);
let ref=0; for(let k=0;k<K;k++) ref += ((0*K+k)%13)*0.25 * ((k*N+0)%5)*0.5;
console.log("matmul C[0]", C.view[0], "exp", ref);
const t0=performance.now(); for(let i=0;i<200;i++) m.exports.matmul(A.ptr,B.ptr,C.ptr,M,K,N);
console.log("matmul 32^3 x200", (performance.now()-t0).toFixed(1)+"ms");
